[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/docker/cli"
  version = "18.06.1"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "bc4c1c238b551ce58fc26690523354d1571bab1d"

# Because docker/go-metrics can not handle the API change after this revision
[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "661e31bf844dfca9aeba15f27ea8aa0d485ad212"
